spring.application.name=Portfolio

# ===============================
# NEON PostgreSQL Database
# ===============================

spring.datasource.url=postgresql://portfolio_user:TTehc4ax2tqZV8Mhb4ffcTulwyf8BZK9@dpg-d8ak2vrbc2fs7383ol2g-a.oregon-postgres.render.com/portfolio_scq8
spring.datasource.username=portfolio_user
spring.datasource.password=TTehc4ax2tqZV8Mhb4ffcTulwyf8BZK9
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Email Configuration
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=abhishekjadhav.official2025@gmail.com
spring.mail.password=bzmq sbvd pgmi ajfp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




